<?php
/**
 *  商品控制器
 * @version  1.0
 * @author   yuanzhenchao
 * @date     2018/5/30
 */
namespace app\webcontroller\controller;

class Goods extends Common{
    private $model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->model=new \app\common\model\Goods();
    }

    public function index()
    {
        //定义数据表格
        $table = [
            ['type' => 'numbers', 'title' => '序号'],
            ['field' => 'goods_name','title' => '商品名称','align'=>'center','width' => 150,],
            ['field' => 'image', 'title' =>'封面图','align'=>'center', 'width' => 100,'templet' => '#tb-image'],
            ['field' => 'starting_price','title' => '起拍价','align'=>'center','width' => 80,],
            ['field' => 'range_price','title' => '加价幅度','align'=>'center','width' => 100,],
            ['field' => 'sort','title' => '排序','align'=>'center','width' => 80,],
            ['field' => 'start_time','title' => '开始时间','align'=>'center','width' => 160,],
            ['field' => 'end_time','title' => '结束时间','align'=>'center','width' => 160,],
            ['field' => 'status','title' => '状态','align'=>'center','width' => 100,'templet' => '#tb-status'],
            //操作标签
            ['fixed'   => 'right','title'   => '操作','width'   => 178,'align'   => 'center','toolbar' => '#tb-action',],
        ];

        $this->assign('table', json_encode($table));

        return $this->fetch();
    }

    /**
     * 数据列表
     * @param string
     * @return json
     */
    public function getData($limit)
    {
        $name = '';
        $data = $this->request->get();
        if(!empty($data['key']['name'])){
            $name = trim($data['key']['name']);
        }
        if($name){
            $data = $this->model->where('name','like',$name.'%')->order('create_time desc,sort asc')->paginate($limit)->toArray();

        }else{
            $data = $this->model->order('create_time desc,sort asc')->paginate($limit)->toArray();
        }
        return $this->result_layui($data['data'], 200, '分类信息', $data['total']);
    }

    /**
     * 新增功能
     */
    public function create()
    {
        // 判断当前操作
        if ($this->request->isAjax()) {
            $request = input();
            if(!empty($request['image'])){
                $request['image'] = implode(',',$request['image']);
            }
            return $this->addAction($request, $this->model);
        }
        return $this->fetch('createEdit');
    }

    /**
     * 编辑功能
     */
    public function edit($id)
    {
        if ($this->request->isAjax()) {
            $request = input();
            if(!empty($request['image'])){
                $request['image'] = implode(',',$request['image']);
            }
            return $this->editActon($request, $this->model);
        }
        $data = $this->model->find($id);
        $data['image'] = explode(',',$data['image']);
        $this->assign('data', $data);
        return $this->fetch('createEdit');
    }

    /**
     * 删除
     */
    public function delete($id)
    {
        return $this->delAction($id, $this->model);
        
    }
}